### ISSUE TITLE
dont transalte

### ISSUE THREAD

**Issue by Ammariq1221** [botbahlul/PyAutoSRT#1]
this program dosent work why?

**Comment by vpgits** [comment]
The original unofficial google translate API seems to be abandoned.

**Comment by botbahlul** [comment]
are you sure? can you show some screenshot?
it's working fine here

**Comment by botbahlul** [comment]
> this program dosent work why?

which part? please upload some screenshot or error traceback call

**Comment by botbahlul** [comment]
> are you sure? can you show some screenshot?
> it's working fine here
> please also check with command line version :

are you sure? can you show some screenshot?
it's working fine here
please also check with command line version :
https://github.com/botbahlul/autosrt
