### ISSUE TITLE
Error: 'name'main_window' is not defined' when translating multiple MP4 files

### ISSUE THREAD

**Issue by diaozheng1226** [botbahlul/PyAutoSRT#10]
![_21 (HKK3% O1 A~8JXH@U3](https://github.com/botbahlul/PyAutoSRT/assets/129975676/d69b7854-c9bf-404a-9946-ee767a806dc1)
Hello, PyAutoSRT-0.2.9 after downloading and using, when translating multiple mp4 files, a popup window appears with the message "name'main_window' is not defined." Is there something I configured incorrectly? I look forward to your response. Thank you.

**Comment by Patlamgoc** [comment]
Same issue here but everything goes fine occasionally, maybe 15% of the time, try relaunching the app until getting a working session as a temporary workaround.

**Comment by botbahlul** [comment]
> ![_21 (HKK3% O1 A~8JXH@U3](https://user-images.githubusercontent.com/129975676/277143999-d69b7854-c9bf-404a-9946-ee767a806dc1.png) Hello, PyAutoSRT-0.2.9 after downloading and using, when translating multiple mp4 files, a popup window appears with the message "name'main_window' is not defined." Is there something I configured incorrectly? I look forward to your response. Thank you.

can you give me those links of videos you tried to transcribe?
