### ISSUE TITLE
ffmpeg executable not found on machine

### ISSUE THREAD

**Issue by erikpedra** [botbahlul/PyAutoSRT#3]
![image](https://user-images.githubusercontent.com/56580637/235087804-bab5197f-6a9d-4faa-89cc-3e97ec507dca.png)

ffmpeg executable not found on machine

**Comment by botbahlul** [comment]
if you're WINDOWS USER download it from here :
```
https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-2023-04-26-git-e3143703e9-full_build.7z
```
then extract that ffmpeg.exe file into C:\Windows\system32\ folder

if you're LINUX USER :
install it using your package manager, e.g. if you're on DEBIAN or UBUNTU you can just type :
```
apt install -y ffmpeg
```

I'VE WROTE ALL OF THESE ON THE FIRST PAGE OF MY REPO, PLEASE READ THAT :)

**Comment by erikpedra** [comment]
Yes, I have saved it in the C:\Windows\system32\ folder, but still get an error
![image](https://user-images.githubusercontent.com/56580637/235128161-493f3d2c-9e06-42cc-bb14-8197501c34b3.png)
