### ISSUE TITLE
open failed

### ISSUE THREAD

**Issue by xs-alpha** [botbahlul/PyAutoSRT#5]
i put these files into environment , and my computer is windows10, the time i double click pyautosrt.exe it shows that 
`Traceback (most recent call last):
  File "pyautosrt.pyw", line 2124, in <module>
  File "pyautosrt.pyw", line 1589, in main
  File "pyautosrt.pyw", line 1543, in stop_ffmpeg_windows
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in `

**Comment by botbahlul** [comment]
Which version?
please try latest version, let me know if you're still get bugs
https://github.com/botbahlul/PyAutoSRT/releases/download/PyAutoSRT-0.1.15/pyautosrt-0.1.15.zip

**Comment by xs-alpha** [comment]
thank for your replying firstly, 
now it can open while i use the latest version, but some questions still exist, 
![image](https://user-images.githubusercontent.com/55642534/236775343-849d7c88-4208-4407-85fb-35d05ac71978.png)

**Comment by botbahlul** [comment]
Aaargh! My bad!
I forgot that single executable need to include all classes and modules from autosrt 1.2.11 inside the script.
You won't get any bugs if you install with pip.
Please try this and inform me if there's still bugs on it.
https://github.com/botbahlul/PyAutoSRT/releases/download/PyAutoSRT-0.1.16/pyautosrt-0.1.16.zip

**Comment by xs-alpha** [comment]
> Please try this and let me know if you're still get bugs https://github.com/botbahlul/PyAutoSRT/releases/download/PyAutoSRT-0.1.17/pyautosrt-0.1.17.zip

so sorry i am late, the time i add a file suffix ended with mp4, it shows that *.mp4 is not a valid audio or video file

**Comment by botbahlul** [comment]
I don't understand what you mean.
What kind of scenario you did?
Is it a command line? Or typing in Browsed File input box? Or just use Add button?

**Comment by botbahlul** [comment]
> > Please try this and let me know if you're still get bugs https://github.com/botbahlul/PyAutoSRT/releases/download/PyAutoSRT-0.1.17/pyautosrt-0.1.17.zip
> 
> so sorry i am late, the time i add a file suffix ended with mp4, it shows that *.mp4 is not a valid audio or video file

please try this update, if you're still get bugs, let me know
https://github.com/botbahlul/PyAutoSRT/releases/download/PyAutoSRT-0.1.18/pyautosrt-0.1.18.zip

**Comment by botbahlul** [comment]
I thinkl I found the culprit.
It looks like the problem came from wrong ffprobe that I zipped in every release.
Please get the latest original ffmpeg from : https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
