### ISSUE TITLE
Not Valid Video or Audio file

### ISSUE THREAD

**Issue by krishan1987** [botbahlul/PyAutoSRT#6]
Sir, 

When I add the file to PyAutoSRT it says not valid video or audio file. but version 0.1.9 is working fine.  
can you help me to solve this? i am not experienced in python to do that
![Screenshot 2023-05-30 223134](https://github.com/botbahlul/PyAutoSRT/assets/53225641/8279de17-af02-4976-ae78-50573ee9e1f7)

**Comment by BobioObio** [comment]
same problem, but its workin on version 0.18

**Comment by botbahlul** [comment]
I just upload version 0.2.0
Please try it and let me know if you're still get some bugs

**Comment by botbahlul** [comment]
> Sir,
> 
> When I add the file to PyAutoSRT it says not valid video or audio file. but version 0.1.9 is working fine. can you help me to solve this? i am not experienced in python to do that ![Screenshot 2023-05-30 223134](https://user-images.githubusercontent.com/53225641/242041004-8279de17-af02-4976-ae78-50573ee9e1f7.png)

I've deleted some old buggy release versions, please try the latest version.
I just added a few features to a new update, so maybe it's still has some bugs.
Please let me know if it's working or not.

**Comment by botbahlul** [comment]
> same problem, but its workin on version 0.18 on my case

I just upload version 0.2.0
Please try it and let me know if you're still get some bugs.

**Comment by krishan1987** [comment]
> > same problem, but its workin on version 0.18 on my case
> 
> I just upload version 0.2.0 Please try it and let me know if you're still get some bugs.

Same Issue sir. But successfully loaded in to 0.1.9
![0 2 1](https://github.com/botbahlul/PyAutoSRT/assets/53225641/088484cd-66be-4731-88d0-3092def93f5f)
 
Any code to execute python ?

**Comment by krishan1987** [comment]
> Same Issue sir. But successfully loaded in to 0.1.9 ![0 2 1](https://user-images.githubusercontent.com/53225641/245193456-088484cd-66be-4731-88d0-3092def93f5f.png)
> 
> Any code to execute python ?

Same Issue sir. But successfully loaded in to 0.1.9
Any code to execute python ?
![0 2 1](https://github.com/botbahlul/PyAutoSRT/assets/53225641/bdbee295-3687-4438-88ae-9c915f9a426c)

**Comment by botbahlul** [comment]
I thinkl I found the culprit.
It looks like the problem came from wrong ffprobe that I zipped in every release.
Please get the latest original ffmpeg from : https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
