### ISSUE TITLE
Not valid Audio or Video File

### ISSUE THREAD

**Issue by krishan1987** [botbahlul/PyAutoSRT#7]
Sir, 
When i try to import mp4 in to PyAutoSRT it says not valid audio or video file. But it is working on pyautosrt-0.1.9. what would be the reason? can you help to solve this
![srt](https://github.com/botbahlul/PyAutoSRT/assets/53225641/0ccb8a35-698b-4310-ac79-bb7d8400b8aa)

**Comment by botbahlul** [comment]
which version are you using? executable from release page or installed with pip?
and can you send me the video?

**Comment by botbahlul** [comment]
I thinkl I found the culprit.
It looks like the problem came from wrong ffprobe that I zipped in every release.
Please get the latest original ffmpeg from : https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

**Comment by krishan1987** [comment]
> I thinkl I found the culprit. It looks like the problem came from wrong ffprobe that I zipped in every release. Please get the latest original ffmpeg from : https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

Now it finally worked very well. thank you, friend...
